poskus da ne bo crashu če ni artifacta

diff --git a/.github/workflows/28580_test.yml b/.github/workflows/28580_test.yml
--- a/.github/workflows/28580_test.yml
+++ b/.github/workflows/28580_test.yml
@@ -46,13 +46,20 @@ jobs:
         with:
           name: error-file
           path: .
+        continue-on-error: true #pomeni da artifacta ni
+
       #ga peveri. in če je napaka prekine workflow
       - name: Check error file content
         run: |
-          if grep -q "Error details" napaka.txt; then
-            echo "Tests failed due to missing test directory."
-            exit 1
+          if [ -f napaka.txt ]; then
+            if grep -q "Error details" napaka.txt; then
+              echo "Tests failed due to missing test directory."
+              exit 1
+            fi
           fi
+        continue-on-error: true #pomeni da artifacta ni
+
+
         #pripravimo runnerja da bo lahko izvedel teste
       - name: Setup environment
         run: |
